### PR TITLE
Spinsim CI tests

### PR DESCRIPTION
**Pull request by Wuerfel21**
Here they are. I swear these CI runners are some sort of magic powered by unicorn tears, they can build flexspin+spinsim and run the test suite in under a minute.

The submodule points at my spinsim fork, repoint it if you want.

### CODE REVIEW

**Comment by Wuerfel21** [comment]
(Though I wonder if it is possible to set up a Pi or smth as a runner with a P2 attached to run tests on hardware)

**Comment by Wuerfel21** [comment]
Ah, finally merged.
No idea why its busted now. Seems to choke on the bytecode tests. Are these even enabled on my branch?

**Comment by Wuerfel21** [comment]
Oh, I think the 64 bit fmt support is exploding the bytecode backend

**Comment by totalspectrum** [comment]
Yes, the new 64 bit stuff didn't work on bytecode. It's in better shape now, but 64 bit printf isn't working yet. I've checked in a work-around for now.

**Comment by Wuerfel21** [comment]
64 bit constants are busted:
```c
#include <stdint.h>
void main() {
    int64_t a = 0x123456789;
}
```
```
'--- Function main
0018: 3B 23 45 67 89          ' CONSTANT 591751049
001D: 69                      ' MEM_WRITE LONG DBASE+$0008 (short)
001E: 65                      ' MEM_WRITE LONG DBASE+$0004 (short)
001F: 32                      ' RETURN_PLAIN
```
Also, `__int64_add` has a third return val for some reason. Don't fix that, I will do it along with some micro-optimization

**Comment by Wuerfel21** [comment]
I think there's a variable allocation problem with multi-return, too.
This is what `__int64_add` compiles to
```
'--- Function _int64_add
0288: 64                      ' MEM_READ LONG DBASE+$0004 (short)
0289: 6C                      ' MEM_READ LONG DBASE+$000C (short)
028A: EC                      ' MATHOP: ADD
028B: 61                      ' MEM_WRITE LONG DBASE+$0000 (short)
028C: 68                      ' MEM_READ LONG DBASE+$0008 (short)
028D: 70                      ' MEM_READ LONG DBASE+$0010 (short)
028E: EC                      ' MATHOP: ADD
028F: CD 20                   ' MEM_WRITE LONG DBASE+$0020 
0291: 60                      ' MEM_READ LONG DBASE+$0000 (short)
0292: 6C                      ' MEM_READ LONG DBASE+$000C (short)
0293: F9                      ' MATHOP: CMP_B
0294: 0A 03                   ' JUMP_IF_Z +3
0296: CE 20 2E                ' MEM_MODIFY LONG DBASE+$0020  MOD_POSTINC (LONG)
'LABEL
0299: 60                      ' MEM_READ LONG DBASE+$0000 (short)
029A: CC 20                   ' MEM_READ LONG DBASE+$0020 
029C: CC 30                   ' MEM_READ LONG DBASE+$0030 
029E: 3F B5                   ' REG_WRITE 1F5(OUTB)
02A0: 3F B3                   ' REG_WRITE 1F3(INB)
02A2: 33                      ' RETURN_POP
```
Where is it getting DBASE+$30????

**Comment by Wuerfel21** [comment]
Also I think unsigned compares are busted.

**Comment by Wuerfel21** [comment]
Fixed + optimized would be
```spin
pri _int64_add(alo, ahi, blo, bhi) : rlo, rhi
  rhi := (ahi + bhi) - ((rlo := alo + blo) +< blo)
```

**Comment by totalspectrum** [comment]
I've fixed some of those typos and updated int64_add to be what you suggested. Thanks!

**Pull request merged**
