### PR TITLE
Accurate IsDeadAfter for result regs

### LINKED ISSUE #219: constant propagation doesn't always remove writes to resultXX after function inlining
Using the same example code from issue #218 , compiler fails to eliminate pointless writes to result variables after inlining `_int64_zerox`:
```
_main
	mov	COUNT_, #7
	call	#pushregs_
	mov	arg02, local02
	mov	result2, #0    '<------ 
	mov	result1, #32   '<------ 
	mov	arg03, #32
	mov	arg04, #0
	mov	arg01, ##19088743
	call	#__system___int64_shl
	mov	local03, result1
	add	local03, ##-1985229329 wc
	addx	result2, #0
	mov	local04, result2
	mov	local05, ##@LR__0188
	mov	local06, local04
	mov	result2, #0    '<------
	mov	result1, #32   '<------
	mov	arg03, #32
	mov	arg04, #0
	mov	arg01, local03
	mov	arg02, local06
	call	#__system___int64_shr
	mov	local07, result1
	mov	arg01, local05
	mov	arg02, ptra
	wrlong	local07, ptra++
	wrlong	local03, ptra++
	call	#_printf
	sub	ptra, #8
	mov	arg01, local03
	mov	arg02, local06
	mov	arg03, #1
	call	#_ohno2_0003
	mov	ptra, fp
	call	#popregs_
_main_ret
	ret
```

### PR DESCRIPTION
**Pull request by Wuerfel21**
Not sure if I put REG_RESULT into all the relevant switches and conditions, but seems good. Fixes #219.

Based on #245's branch because I forgot to change to master.

### CODE REVIEW

**Comment by Wuerfel21** [comment]
Just noting: one of the exec tests breaks on this branch, investigation in progress

**Comment by Wuerfel21** [comment]
Something something lambdas, it seems. But it seems that the codegen is bung to begin with and relies on `__system__bytemove` not to touch `result6`, whereas my PR assumes that results may be destroyed by any function call.

Why `result6`, anyways? Where did 2 through 5 go?

**Comment by Wuerfel21** [comment]
Seems that was deliberate. Replaced it with a temp register use, which isn't the greatest, but these sequences are pretty jank to begin with, so the extra local isn't going to hurt so much (if it even is "extra". Aside from being a temp reg, given the limited lifetime the #234 code can just make it disappear)

**Comment by totalspectrum** [comment]
Thanks, this looks good.

**Pull request merged**
