### PR TITLE
Add CMake support

### PR DESCRIPTION
**Pull request by DavidZemon**
This is on the master branch for the moment, but I could move it to the experimental branch, or rebase the expiremental branch onto master if you'd like.

Main targets supported:

* all: compile all executables (spin2cpp and testlex)
* test-all: Run all unit tests
* install: Install files (spin2cpp -> `${DESTDIR}/${PREFIX}/bin` and other files go into `${DESTDIR}/${PREFIX}/docs`)
* package: Builds a zip and tarball as well as rpm, deb, and exe installers (individual packages can be built with `cpack -G <NAME>` such as `cpack -G ZIP`)

To compile, I recommend something like the following:

```bash
git clone ...
cd spin2cpp
mkdir bin
cd bin

mkdir linux
cd linux
cmake ../..
make test-all
cd ..

mkdir rpi
cd rpi
cmake -D CROSS=rpi ../..
make # Can't run tests here
cd ..

mkdir win32
cd win32
cmake -D CROSS=win32 ../..
make test-all # Works if you have wine installed
```

### CODE REVIEW

**Comment by DavidZemon** [comment]
Okay, I've replaced all unit testing with native CMake implementations. There is one problem though, and that is the debug and error tests use absolute file paths when run via CMake, but the expected output has relative paths. This causes failures even though spin2cpp is executing correctly. Fixing this requires one of a few options:

1. Run the tests in the source directory (not a fan - this ruins the wonderful out-of-source nature of CMake)
2. Copy the source file to the binary directory before running the test
3. Using a tool other than a straight diff, something to search for "string in file" rather than "file equals file"

**Comment by DavidZemon** [comment]
`b72c826` was removed and replaced by `8f4f7a1`.

I've implemented option 2. This has all tests passing except error03. The output summary from the `test-all` target looks like this:

```
99% tests passed, 1 tests failed out of 149

Label Time Summary:
cpptests        =   0.51 sec (125 tests)
ctests          =   0.01 sec (2 tests)
debugtests      =   0.01 sec (2 tests)
errortests      =   0.02 sec (6 tests)
runtimetests    =  25.57 sec (13 tests)

Total Test time (real) =  26.14 sec

The following tests FAILED:
        132 - error03 (Failed)
Errors while running CTest
```

**Comment by DavidZemon** [comment]
I've rebased onto your latest changes and the old tests are still passing (except for error03 still). I haven't updated the CMake test scripts to run any new tests that may have been written since March 6.

**Comment by totalspectrum** [comment]
Sorry, I'm just too  attached to my current build procedure. CMake seems nice, but I'm not ready to switch yet.

**Pull request closed without merging**
