### PR TITLE
Fix new augmentation check for P1

### PR DESCRIPTION
**Pull request by Wuerfel21**
As far as I can tell this isn't qualified for P2-only anywhere else. If putting the check somewhere else feels nicer, do that.

### CODE REVIEW

**Comment by totalspectrum** [comment]
I'm not sure this matters for P1, since we won't be able to generate immediate operands that would need augments there. So the values should always be in [0,511].

**Comment by Wuerfel21** [comment]
Does FCACHE-ing happen after large immediate are converted to registers?

**Comment by totalspectrum** [comment]
> Does FCACHE-ing happen after large immediate are converted to registers?

Yes; actually large immediates are converted to registers at the time they're generated in NewImmediate().

**Comment by Wuerfel21** [comment]
Ah, never noticed that. But they're IMM_INT either way and therefore would mess up this check. I guess it should be checking whether the name is empty instead of checking value?

**Comment by totalspectrum** [comment]
Oh, I see. Well, no harm in adding the gl_p2 check, so I'll merge this.

**Pull request merged**
