### PR TITLE
Bytecode backend...

### PR DESCRIPTION
**Pull request by Wuerfel21**
So far, can compile simple programs like this into working, but not very good Spin1 bytecode (use `--interp=rom`):
```spin1
PUB main
  dira[10]:=1
  repeat while 123
    outa[10]^=1
```
```
0000: 00 B4 C4 04             ' CLKFREQ
0004: 6F                      ' CLKMODE
0005: 00                      ' Placeholder for checksum
0006: 10 00                   ' PBASE
0008: E8 7F                   ' VBASE
000A: F0 7F                   ' DBASE
000C: 18 00                   ' PCURR
000E: F8 7F                   ' DCURR
'--- Object Header for blink
0010: 00 00                   ' Object size(?)
0012: 02                      ' Method count + 1
0013: 00                      ' OBJ count
0014: 08 00 00 00             ' Function main @0018 (local size 0)
'--- Function main
0018: 3F 96                   ' REG_READ 1F6
001A: 36                      ' PUSH_IMM 1
001B: 38 0A                   ' PUSH_IMM 10
001D: E3                      ' MATHOP: SHL
001E: EA                      ' MATHOP: BITOR
001F: 3F B6                   ' REG_WRITE 1F6
'LABEL
0021: 38 7B                   ' PUSH_IMM 123
0023: 0A 0A                   ' JUMP_IF_Z 10
0025: 3F 94                   ' REG_READ 1F4
0027: 39 04 00                ' PUSH_IMM 1024
002A: EB                      ' MATHOP: BITXOR
002B: 3F B4                   ' REG_WRITE 1F4
002D: 04 72                   ' JUMP -14
'LABEL
002F: 32                      ' RETURN_PLAIN
```

What works:
 - Integer literals
 - Some binary math operators
 - register read/write
 - REPEAT WHILE loops (and also REPEAT for reasons mentioned below)

Potential Problems:
 - Obviously needs a lot more work (thus the draft-type PR you can't actually merge). The binary header is completely fake...
 - Not sure if I bolted the new backend on right
 - The way listings work for ASM output is to generate an ASM file and then compile that again. Since IMO a similar approach would be ludicrous for bytecode, I just wrote a separate listing system. That OK?
 - The parser is loosing some details (like turning REPEAT into REPEAT WHILE 1 and similar things). I can detect the patterns and optimize them back, but one of my goals is to get the same binary as the other spin compilers (to allow for bulk testing), so these de-optimized constructs must be marked in some way to be optimized even if the optimization is normally disabled. How might I add such info to AST nodes? Just add a new field?
 - The variable allocation stuff all happens in the ASM backend, right? Would that be easy to hook into or should I write another one? haven't looked into this much yet.
 -  (solved) ~~DATs. The C backend compiles them straight into raw data, so I think that'll be easy to reuse?~~

### CODE REVIEW

**Comment by Wuerfel21** [comment]
Just tried adding WAITCNT and friends for the full blinking LED experience, [but ran into a snag wherein it won't give me SYM_BUILTIN symbols for it](https://github.com/Wuerfel21/spin2cpp/blob/W21-bytecode/backends/bytecode/outbc.c#L165), just normal SYM_FUNCTION. Considering SYM_BUILTIN is only used in the C backend, I presume that somewhere the builtins get transformed into normal function calls, which needs to be disabled, but I can't seem to find it.

**Comment by totalspectrum** [comment]
At a quick glance it looks like you're on the right track with this. A few comments:

(1) A separate listing system for bytecode makes sense.
(2) I wouldn't put any effort into pessimizing code. "REPEAT" and "REPEAT WHILE TRUE" should generate the same thing. I realize the other Spin compilers don't do this, but on the other hand we do have all of those Spin compilers. I don't think we need to re-invent openspin, homespun, bstc, etc.
(3) Variable allocation in ASM is a bit of a mess, and basically relies on label resolution happening in the second pass. You probably want to do it differently for bytecode.
(4) SYM_BUILTIN is also a mess. It was invented for the C backend, and turned out not to be useful at all for the ASM backend, so it's bit-rotted somewhat.

**Comment by Wuerfel21** [comment]
> (2) I wouldn't put any effort into pessimizing code. "REPEAT" and "REPEAT WHILE TRUE" should generate the same thing. I realize the other Spin compilers don't do this, but on the other hand we do have all of those Spin compilers. I don't think we need to re-invent openspin, homespun, bstc, etc.

It's more undoing the pessimization that the parser does, so it's not a lot of effort to make it conditional.
The point of that would be to enable mass testing, i.e. pass all spin source from the OBEX through openspin/homespun/whatever and flexspin and see if the binaries comes out different. Would also be useful for Spin2 since there isn't an open reference compiler for it . I've also seen some code that relies on the particular location of certain bytecodes to do some hacks like dynamically dispatching to different functions, but that's like, mega fringe.
I think adding a bool flag `parser_pessimized` to AST shouldn't make everything else explode, so that's what I think i'll do when it's time to add the relevant optimizations. It'll still do the normal checks for that optimization so if the AST optimizations took care of it it won't do a silly thing.

> (3) Variable allocation in ASM is a bit of a mess, and basically relies on label resolution happening in the second pass. You probably want to do it differently for bytecode.

OK, gotta write a new one... Just got memory ops working on the DAT section, so slotting VARs/locals in there shouldn't be a problem now. Should be able to support access to subobject variables, too.

> (4) SYM_BUILTIN is also a mess. It was invented for the C backend, and turned out not to be useful at all for the ASM backend, so it's bit-rotted somewhat.

So how do I figure out if a function call is a builtin then? (since their names are different per-language)

**Comment by totalspectrum** [comment]
There are a lot of things that the higher level code "canonicalizes", e.g. "a += b" gets turned into "a := a + b", loops get turned into normal form, and even some operators like |< get turned into <<. I don't think it's feasible to make flexspin produce exactly the same binary output as openspin. Nor do I think it's really necessary. Yes, binary testing would be nice, but it can still be done in some cases (as long as you avoid the changes made by the parser and the high level code transformations).

**Comment by totalspectrum** [comment]
For builtin functions... I'm not sure what the best approach to this is. If you can use SYM_BUILTIN great, I just wanted to warn you that it may have some bugs.

**Comment by Wuerfel21** [comment]
I think I figured out why I'm not getting builtins: I think it's pulling in the code from `sys/p1_code.spin`, which defines waitcnt and the other builtins in terms of inline ASM. Now to figure out what the C backend does to not make that happen.

**Comment by Wuerfel21** [comment]
Ahhhh, I didn't actually set `gl_output` to `OUTPUT_BYTECODE`. owie ouch.

**Comment by Wuerfel21** [comment]
> (3) Variable allocation in ASM is a bit of a mess, and basically relies on label resolution happening in the second pass. You probably want to do it differently for bytecode.

Uhh, it seems something is already allocating them, since it seems I can just grab `Symbol::offset` and get a seemingly correct offset.

**Comment by Wuerfel21** [comment]
Same thing for the locals, seems to just work:tm:. Though I haven't figured out the right way to get the total size of the locals/parameters.

Also, using RESULT seems to insert an explicit return of it into the AST, gotta figure out a way to get rid of that.

**Comment by Wuerfel21** [comment]
I've ran across one loop transformation that seems like a real pain to reverse, which is that `REPEAT N` gets turned into a loop with a temporary that is already allocated in the local array. So to get that back to a simple counted loop and remove the explicit counter and use the implicit stack counter instead, I'd have to
 - Figure out if that temporary variable really is only used in the loop
 - Remove it from the locals, shifting down the offsets of all locals that theoretically follow it
 - This all before actually starting to compile the function, so that variable accesses above the loop don't use the wrong offset, thus that has to be another entirely separate AST walking pass
 
Or is there a less silly way of doing this?

**Comment by totalspectrum** [comment]
The loop variable is created in loops.c, near line 1399 (the comment reads "get the loop variable, if we don't already have one"). You *may* be able to check for bytecode output and abort the whole process at that point by returning the original AST in "origast". Alternatively, you could check in the AST_COUNTREPEAT case in frontends/spin/spinlang.c, function doSpinTransform (near line 599) and skip the call to TransformCountRepeat for bytecode output.

**Comment by Wuerfel21** [comment]
Thanks for the info, will mess with that tomorrow

**Comment by Wuerfel21** [comment]
Just added boolean operators, both the LOGIC and BOOL variants. 
LOGIC just becomes the relevant opcode and BOOL is implemented as such:
 - if in a value expression, convert to LOGIC if right has no side effect.
 - if in value expression and with side effects, compile rickety construct to return 0 or -1
 - if in conditional expression, just compile multiple jumps

Short circuit conditions increase code size a little and in simple cases like AND-ing two locals, likely are also slower (haven't checked). Is there a way to guesstimate the complexity of an expression, so as to use LOGIC for simple ones? (Additionally, it may be a good idea to introduce an -Os mode that always uses the smaller option. Not sure if it'd be a big enough difference to warrant that)

**Comment by Wuerfel21** [comment]
Haven't actually checked in on the loop thing yet, but here's another one that creates a pointless temp variable: `x += z++` turns into an AST_SEQUENCE where it increments into a temp var and then does the add with that.

**Comment by Wuerfel21** [comment]
Also, just disabled the transform for LOOKDOWN/LOOKUP, mostly out of laziness to implement the AST_TEMPARRAYUSE, haha. Table would be faster and in some cases smaller, so I'm writing this now mostly as a reminder to revisit it later.

**Comment by Wuerfel21** [comment]
Just added case. Similar to LOOKUP/LOOKDOWN, I disabled transforms for it, since the interpreter has special instructions for it. In this case though, a table implementation would be very advantageous. Aside from increased speed, a word-sized table entry is smaller than a case check (at least 3 (only for -1,0,1), usually 4, up to 7 bytes for constant expression).

**Also, QUITing a loop from inside a case WILL break right now**. Still have to deal with popping of hidden variables.

**Comment by Wuerfel21** [comment]
Oh, and CASE seems to not actually work, since it turns out that statements that aren't on the same line as the case end up on the same level as the case. Can handle it, but can't do the optimization where OTHER is at the top anymore, have to treat it more like the other cases and insert a jump to it. Not a biggie and I think I can undo this later in a peephole pass though, so all is well.

**Comment by Wuerfel21** [comment]
Good enough for a round of Spintris now :)
Screenshot 2021-05-31 15-10-04

**Comment by Wuerfel21** [comment]
Okay, just did the loop stuff.
I think it would be in good enough shape now to merge the work so far. It is still missing loads of optimizations, but it's already decently competitive with PropTool on size and speed. It's also probably full of bugs and missing features.

Problems to that:
 - There's currently loads of debug printf in there. I should probably remove those?
 - Most of my files don't have copyright headers right now. What should I put there?
 - There aren't any tests. Running the tests is kindof obnoxiously slow for me, so I kind of put it off.
 - Currently `-Oloop-reduce` explodes due to post-set instructions it doesn't like (not an issue since bytecode defaults to no optimizations at the moment, but `-O1` seems to work fine)

**Comment by Wuerfel21** [comment]
Just added a few neat peephole optimizations:
 - bytecode-level dead code removal
 - Remove pointless jumps (target label directly after unconditional jump)
 - Contract memory write+read into single modify op (saves a byte if it needs a non-short opcode, and presumably some cycles in all cases)

**Comment by totalspectrum** [comment]
Thank you for all the work you've put into this! Some comments:

- Looks like you've already started removing the debug printfs. If you'd like we could probably make a DEBUG() function similar to WARNING and ERROR but which only prints when some flag is given on the command line. Although personally I prefer to debug using gdb; there are some utility functions like DumpAST() and DumpIRL() which make this even easier.
- Copyright notices are totally up to you, since it's your code. Making the copyright MIT (or at least MIT compatible) would be nice, since it would make all of the code consistently licensed. If you want to use a more restrictive copyright (like GPL) then we'd need to change the Makefile so that we could build different binaries for the different licenses -- I'd still like to distribute an MIT licensed "base version"
- I think a bunch of the executable tests are "plain" Spin (I used to run them with openspin to verify compliance). I'll look into extending these to deal with bytecode
- How would you like to be credited in the README? I could use your forum name, your real name, your company's name, or whatever you'd prefer.

**Comment by Wuerfel21** [comment]
> * Looks like you've already started removing the debug printfs. If you'd like we could probably make a DEBUG() function similar to WARNING and ERROR but which only prints when some flag is given on the command line. Although personally I prefer to debug using gdb; there are some utility functions like DumpAST() and DumpIRL() which make this even easier.

Adding a DEBUG() seems like a great idea. I've currently got some NOTEs about fine-but-questionable code (such as usage of temp variables, which is very rarely actually required in bytecode mode) that probably shouldn't be enabled by default, so that'd be perfect for that, too. What color would it be though? :smiley: I'm thinking purple.

> * Copyright notices are totally up to you, since it's your code. Making the copyright MIT (or at least MIT compatible) would be nice, since it would make all of the code consistently licensed. If you want to use a more restrictive copyright (like GPL) then we'd need to change the Makefile so that we could build different binaries for the different licenses -- I'd still like to distribute an MIT licensed "base version"

Yeah, MIT is fine.

> * How would you like to be credited in the README? I could use your forum name, your real name, your company's name, or whatever you'd prefer.

Real name is ok.

**Comment by Wuerfel21** [comment]
Just added some more neat peepholes:
- consecutive labels can be combined
- a label-to-terminal block that follows a terminal op and is referenced only by a single unconditional jump can be moved into place of the jump. Large blocks aren't moved because it may hurt more than it helps in those cases, but in many cases, it saves a few bytes
- contract some return constructions. Mostly because the frontend/transforms sometimes add a `return result`, but also optimizes writing result directly before a return into a pop return.

**Comment by Wuerfel21** [comment]
As expected, fixing #132 lead to better code quality in bytecode mode

**Comment by Wuerfel21** [comment]
Just added the DEBUG() thing

**Comment by Wuerfel21** [comment]
Unless there's bugs that come up, I think I'm mostly done for now. 

Things still missing: 
 - Tests
 - CASE as jump table
 - Support for some flexspin-isms (`obj.var`, object pointers, etc)

**Comment by totalspectrum** [comment]
This is looking good, Ada, thanks! I'll be reviewing and hope to merge it into master branch today or tomorrow.

**Pull request merged**
