### PR TITLE
Slightly reduce size of gcalloc in bytecode mode

### PR DESCRIPTION
**Pull request by Wuerfel21**
Was a bit bugged by slightly sub-optimal code in there while investigating something else.
This makes the alloc code about 12 bytes smaller and probably a tad faster, too.
PASM output is unchanged save for some reordered instructions.

Most of these have to do with replacing explicit `return 0` with implicit return of the zero-initialized result variable, which seems like it should be able to happen automatically, but IDK how to robustly detect that condition. The PASM backend seems to have some solution to that?
The other thing is moving one of the locals into the otherwise-unused RESULT slot. In Spin, I'd just expect the programmer to do this, but for other languages, might be nice to have a heuristic select a local to place into the RESULT slot.

### CODE REVIEW

**Comment by totalspectrum** [comment]
I like being able to explicitly show the return value ("return ptr" instead of "return").  I wonder how hard it would be to optimize that in the bytecode backend? I haven't looked at that code yet.

**Comment by Wuerfel21** [comment]
Oh, `return result` is optimized to plain return, that's never an issue.

**Comment by totalspectrum** [comment]
I've added a small optimization to make "return ptr" and "return" the same in the case where "ptr" is the return value, and also to make "return 0" and "return" the same where there is no explicit return variable and RESULT is not set. I've merged a few of your other changes to gcalloc.spin manually. Thanks for the ideas!

**Comment by Wuerfel21** [comment]
Uhh, the `return result` case was already being handled at the IR level

**Comment by Wuerfel21** [comment]
(Nevermind, just realized that that also catches the zero result case)

**Pull request closed without merging**
