### PR TITLE
Reconsider leaf functions after inlining

### PR DESCRIPTION
**Pull request by Wuerfel21**
Not sure if there's any edge-cases I overlooked, but seems to be fine.

Note that this makes #302 occur more often, so probably fix that one before/after merging this.

### CODE REVIEW

**Comment by Wuerfel21** [comment]
Actually, I do think there is an issue, because the assumption that the leaf function doesn't use any argXX that it doesn't directly take is violated...

**Comment by Wuerfel21** [comment]
Okay, reworked it to avoid that issue (and also to use a separate flag in bedata instead of messing with the actual is_leaf).

Now that I think about it, there's some more optimization potential from analyzing intermediate code and then optimizing around call-sites again. Say, if a function does not use any CORDIC ops, a call to it can be reordered inside one. If there's no WRLONG we can forward loads across it, etc.

**Comment by totalspectrum** [comment]
I think I'll wait on this until I understand #302 better.

**Comment by Wuerfel21** [comment]
I think I figured it out, PR incoming

**Comment by totalspectrum** [comment]
Thanks. I just baked a release, but all of these changes will be a nice start on the next version.

**Pull request merged**
