### PR TITLE
Colorize error output

### PR DESCRIPTION
**Pull request by Wuerfel21**
Because I kept missing them in seas of debug prints. Also looks pretty nice.

Windows doesn't really support ANSI, so it needs a separate code path using special sauce APIs. Thus I didn't really test the ANSI output, hope it works.

Is automatically enabled/disabled based on whether stderr is attached to a TTY, but can also be overridden using `--color` and `--nocolor`

image

### CODE REVIEW

**Comment by Wuerfel21** [comment]
Oop, stupid phone github app did this ^

**Comment by avsa242** [comment]
Nice! I've thought about asking for this in the past, but didn't bother. The ANSI output seems to work fine here.

**Comment by Wuerfel21** [comment]
Ah, thanks for verifying that

**Comment by totalspectrum** [comment]
This looks interesting, thank you. I'm going to test it with FlexProp and make sure it still works there.

**Comment by Wuerfel21** [comment]
If FlexProp is just capturing the process output, it shouldn't do anything, since that doesn't count as a TTY. Though it has a terminal, too, so maybe it does count as a TTY? If it detects a TTY or you force it with `--color`, it'll just give you the ANSI escapes on Linux and nothing on Windows (Setting color on something that isn't a CSRSS/conhost console is a no-op. May set an error flag, IDK, but doesn't seem to hurt)

**Pull request merged**
