### PR TITLE
Add BRK Debugger for PASM

### PR DESCRIPTION
**Pull request by Wuerfel21**
Not quite ready for prime time yet, but works!
```spin
CON
_CLKFREQ = 10_000_000
{PUB main()
coginit(1,@entry,0)
}
DAT
org 0
entry
mov pa,#0
.loop
drvnot #56
waitx ##_CLKFREQ/4
debug("Hello Debug! ",udec(pa),if(#0),uhex_long(.loop))
add pa,#1
jmp #.loop
```
compile and load with
```
flexspin -2 -gbrk debugtest.spin2
loadp2 -t -b 2000000 debugtest.binary
```

Work still needed:
 - [x] ~~many expressions turn into `"expression"` (cog symbols work though). Ideally we'd yoink the string corresponding to the AST node from the source buffer, but that's currently not tracked, not sure how difficult that'd be to add. Would also improve error messages though.~~
 - [x] ~~does not work when there's a Spin function, loads of weird errors (uncomment `main` to see what I mean). Any idea? The code to build the debug blob is kinda jank, I guess.~~
 - [x] ~~gets wrong clock settings when used with Spin~~
 - [ ] Spin code should probably use the BRK debugger, too, when it is present. It's not too complicated, just have to push all the expressions onto the stack, pop them back off and then do a BRK.
 - [ ] Should make sure that HLL print functions don't interfere too much (use lock 15, don't reconfigure pin 62)

### CODE REVIEW

**Comment by totalspectrum** [comment]
Re: "expression": We don't keep track of columns right now, so pulling the original source out of the AST would be hard (we can get the whole line, but not a sub-expression).

An alternative might be to re-construct the original expression using something like the C backend expression printer. That's already there, but needs some flags to prevent it from mangling DAT section symbols into offsets into the section. Here's a patch that's kind of quick and dirty but seems to work for some simple things:
```
diff --git a/backends/becommon.h b/backends/becommon.h
index 800768b1..a055c2f1 100644
--- a/backends/becommon.h
+++ b/backends/becommon.h
@@ -70,4 +70,37 @@ Flexbuf CompileBrkDebugger(size_t appsize);
 void PrintDataBlock(Flexbuf *f, AST *list, DataBlockOutFuncs *funcs, Flexbuf *relocs);
 void PrintDataBlockForGas(Flexbuf *f, Module *P, int inlineAsm);
 
+/* flags for PrintExpr and friends */
+#define PRINTEXPR_DEFAULT    0x0000
+#define PRINTEXPR_GAS        0x0001  /* printing in a GAS context */
+#define PRINTEXPR_ASSIGNMENT 0x0002  /* printing from an assignment operator */
+#define PRINTEXPR_ISREF      0x0004  /* expression used as a reference */
+#define PRINTEXPR_GASIMM     0x0008  /* GAS expression is an immediate value (so divide labels by 4) */
+#define PRINTEXPR_GASOP      0x0010  /* GAS expression used in an operand */
+#define PRINTEXPR_GASABS     0x0020  /* absolute address, not relative */
+#define PRINTEXPR_USECONST   0x0040  /* print constant names, not values */
+#define PRINTEXPR_TOPLEVEL   0x0080  /* leave out parens around operators */
+#define PRINTEXPR_USEFLOATS  0x0100  /* print  expression as floats if appropriate */
+#define PRINTEXPR_INLINESYM  0x0200  /* printing symbols in inline assembly */
+#define PRINTEXPR_FORCE_UNS  0x0400  /* force arguments to be unsigned */
+#define PRINTEXPR_DEBUG      0x0800  /* print symbols for DEBUG */
+
+/* printing functions */
+void PrintTypedExpr(Flexbuf *f, AST *casttype, AST *expr, int flags);
+void PrintExpr(Flexbuf *f, AST *expr, int flags);
+void PrintLHS(Flexbuf *f, AST *expr, int flags);
+void PrintBoolExpr(Flexbuf *f, AST *expr, int flags);
+void PrintAsAddr(Flexbuf *f, AST *expr, int flags);
+void PrintExprList(Flexbuf *f, AST *list, int flags, Function *func);
+void PrintType(Flexbuf *f, AST *type, int flags);
+void PrintCastType(Flexbuf *f, AST *type);
+void PrintPostfix(Flexbuf *f, AST *val, int toplevel, int flags);
+void PrintInteger(Flexbuf *f, int32_t v, int flags);
+void PrintFloat(Flexbuf *f, int32_t v, int flags);
+int  PrintLookupArray(Flexbuf *f, AST *arr, int flags);
+void PrintGasExpr(Flexbuf *f, AST *expr, bool useFloat);
+void PrintSymbol(Flexbuf *f, Symbol *sym, int flags);
+void PrintObjConstName(Flexbuf *f, Module *P, const char* name);
+void PrintStatementList(Flexbuf *f, AST *ast, int indent);
+
 #endif /* BACKEND_COMMON_H */
diff --git a/backends/brkdebug.c b/backends/brkdebug.c
index c05b91d6..4aff3996 100644
--- a/backends/brkdebug.c
+++ b/backends/brkdebug.c
@@ -217,8 +217,12 @@ int AsmDebug_CodeGen(AST *ast) {
                         flexbuf_putc('#',f);
                         exprAst = exprAst->left;
                     }
-                    const char *expr = GetUserIdentifierName(exprAst);
-                    flexbuf_addstr(f,expr);
+                    if (IsIdentifier(exprAst)) {
+                        const char *expr = GetUserIdentifierName(exprAst);
+                        flexbuf_addstr(f,expr);
+                    } else {
+                        PrintExpr(f, exprAst, PRINTEXPR_DEBUG);
+                    }
                     flexbuf_putc(0,f);
                 }
 
diff --git a/backends/cpp/cppexpr.c b/backends/cpp/cppexpr.c
index bf6aefcf..5ba2f339 100644
--- a/backends/cpp/cppexpr.c
+++ b/backends/cpp/cppexpr.c
@@ -73,7 +73,7 @@ PrintLabel(Flexbuf *f, Symbol *sym, int flags)
         } else {
             flexbuf_printf(f, "_lbl_(%s)", sym->user_name);
         }
-    } else if (current->gasPasm) {
+    } else if (current->gasPasm || (flags & PRINTEXPR_DEBUG)) {
         flexbuf_printf(f, "%s", sym->user_name);
     } else {
         flexbuf_printf(f, "(%s(", ref ? "" : "*");
diff --git a/backends/cpp/outcpp.h b/backends/cpp/outcpp.h
index 76088a9a..fc5d6ad2 100644
--- a/backends/cpp/outcpp.h
+++ b/backends/cpp/outcpp.h
@@ -9,6 +9,7 @@
 #define OUTCPP_H_
 
 #include "util/flexbuf.h"
+#include "becommon.h"
 #include "cppfunc.h"
 
 //
@@ -61,38 +62,6 @@ int PrintPublicFunctionDecls(Flexbuf *f, Module *P);
 int PrintPrivateFunctionDecls(Flexbuf *f, Module *P);
 void PrintFunctionBodies(Flexbuf *f, Module *P);
 
-/* flags for PrintExpr and friends */
-#define PRINTEXPR_DEFAULT    0x0000
-#define PRINTEXPR_GAS        0x0001  /* printing in a GAS context */
-#define PRINTEXPR_ASSIGNMENT 0x0002  /* printing from an assignment operator */
-#define PRINTEXPR_ISREF      0x0004  /* expression used as a reference */
-#define PRINTEXPR_GASIMM     0x0008  /* GAS expression is an immediate value (so divide labels by 4) */
-#define PRINTEXPR_GASOP      0x0010  /* GAS expression used in an operand */
-#define PRINTEXPR_GASABS     0x0020  /* absolute address, not relative */
-#define PRINTEXPR_USECONST   0x0040  /* print constant names, not values */
-#define PRINTEXPR_TOPLEVEL   0x0080  /* leave out parens around operators */
-#define PRINTEXPR_USEFLOATS  0x0100  /* print  expression as floats if appropriate */
-#define PRINTEXPR_INLINESYM  0x0200  /* printing symbols in inline assembly */
-#define PRINTEXPR_FORCE_UNS  0x0400  /* force arguments to be unsigned */
-
-/* printing functions */
-void PrintTypedExpr(Flexbuf *f, AST *casttype, AST *expr, int flags);
-void PrintExpr(Flexbuf *f, AST *expr, int flags);
-void PrintLHS(Flexbuf *f, AST *expr, int flags);
-void PrintBoolExpr(Flexbuf *f, AST *expr, int flags);
-void PrintAsAddr(Flexbuf *f, AST *expr, int flags);
-void PrintExprList(Flexbuf *f, AST *list, int flags, Function *func);
-void PrintType(Flexbuf *f, AST *type, int flags);
-void PrintCastType(Flexbuf *f, AST *type);
-void PrintPostfix(Flexbuf *f, AST *val, int toplevel, int flags);
-void PrintInteger(Flexbuf *f, int32_t v, int flags);
-void PrintFloat(Flexbuf *f, int32_t v, int flags);
-int  PrintLookupArray(Flexbuf *f, AST *arr, int flags);
-void PrintGasExpr(Flexbuf *f, AST *expr, bool useFloat);
-void PrintSymbol(Flexbuf *f, Symbol *sym, int flags);
-void PrintObjConstName(Flexbuf *f, Module *P, const char* name);
-void PrintStatementList(Flexbuf *f, AST *ast, int indent);
-
 typedef struct cppInlineState {
     AST *outputs;
     AST *inputs;
```

**Comment by Wuerfel21** [comment]
Yeah, that patch works fine-ish. Certainly better than just "expression", but kinda weird because of the C-style operators.

**Comment by Wuerfel21** [comment]
Ok, I think the "MVP" has been achieved, ready to merge when you are.

**Comment by totalspectrum** [comment]
Thanks, we may as well get it in, it's certainly better than what was there before :).

**Comment by Wuerfel21** [comment]
Note on the changelog: should clarify to say that it only works in PASM right now, Spin DEBUG still goes the printf route and I'm not sure if using both will mess stuff up.

Will probably look at that tomorrow, idk

**Comment by Wuerfel21** [comment]
>Will probably look at that tomorrow, idk

So, uh, that didn't happen. So next tomorrow I guess. >_<

**Pull request merged**
