### PR TITLE
Add local reuse optimization

### PR DESCRIPTION
**Pull request by Wuerfel21**
Thought of this while messing with the move forwarding. Gets rid of extraneous local registers. Also sometimes makes other optimizations possible. Downside is that it makes the pre-rename register names effectively meaningless (as it can and will swap two locals for no added benefit sometimes). I guess this one mostly helps on P1.

Note that this is based on the branch from #233

### CODE REVIEW

**Comment by Wuerfel21** [comment]
Hmm, this doesn't seem to work under -O2. #223 is fine, so bug must be in the one commit unique to this branch

**Comment by Wuerfel21** [comment]
I think `IsDeadAfter` may infact be busted....
image

**Comment by Wuerfel21** [comment]
I think I figured it: If `IsDeadAfter` is called on the only instruction in a loop that uses a register (modifies of that register ignored), it exits out returning true because it found the loop before it gets to checking that instruction itself, thus missing the dependency.

**Comment by Wuerfel21** [comment]
Seems I fixed it. Also made it able to use arg registers to replace a local, which makes it even more powerful (some functions go to zero locals with this -> no function prologue/epilogue needed anymore). But it can only use args that are actually used in the function....

**Comment by totalspectrum** [comment]
This seems to have some problems, e.g. for stest174.c it generates the code:
```
_blah
	rdlong	blah_tmp004_, ptr__dat__
	rdlong	blah_tmp004_, blah_tmp004_
	mov	blah_tmp002_, blah_tmp004_
	add	blah_tmp004_, #4
	rdlong	blah_tmp004_, blah_tmp004_
	mov	blah_tmp006_, objptr
...
```
blah_tmp004_ was still in use as a pointer but got re-used as a rdlong target :(.

**Comment by Wuerfel21** [comment]
(Assuming you mean stest153, because that's the one that actually contains that code)

That's not actually the bug. It's supposed to be a read of a pointer. The actual bug is that one of the rdlongs inexplicably turns into a move

```diff
 _blah
 	rdlong	blah_tmp004_, ptr__dat__
-	rdlong	blah_tmp001_, blah_tmp004_
-	rdlong	blah_tmp002_, blah_tmp001_
-	add	blah_tmp001_, #4
-	rdlong	blah_tmp003_, blah_tmp001_
+	rdlong	blah_tmp004_, blah_tmp004_
+	mov	blah_tmp002_, blah_tmp004_
+	add	blah_tmp004_, #4
+	rdlong	blah_tmp004_, blah_tmp004_
 	mov	blah_tmp006_, objptr
 	mov	objptr, blah_tmp002_
-	call	blah_tmp003_
+	call	blah_tmp004_
 	mov	objptr, blah_tmp006_
 _blah_ret
 	ret
```

**Comment by Wuerfel21** [comment]
Will see if I can figure the mystery out tomorrow...

**Comment by Wuerfel21** [comment]
(In bed now) oh, duh, there's a missing check for src==dst in the code that turns same-source reads into moves (you know, the one that calls FindNextRead). Can you fix that and try again?

**Comment by Wuerfel21** [comment]
Okay, fixed it, also got rid of the merge conflicts (silly git)

**Comment by Wuerfel21** [comment]
Actually, there's still some weird pessimisations I'm seeing in the tests, but I think it's at least all correct now. Will look further into it later.

**Comment by totalspectrum** [comment]
Thank you for fixing the rdlong a, a being converted to mov bug -- I missed a case there, obviously. We can probably do a little more sophisticated analysis to see if a is ever used again, but for now I think doing the safe thing and avoiding that case is the right thing to do.

I notice that there are now some "mov x, x wz" instructions. Those work fine, of course, but "cmp x, #0 wz" might introduce more opportunities for optimization. I'll try to add a peephole for that later.

**Comment by Wuerfel21** [comment]
> Thank you for fixing the rdlong a, a being converted to mov bug -- I missed a case there, obviously. We can probably do a little more sophisticated analysis to see if a is ever used again, but for now I think doing the safe thing and avoiding that case is the right thing to do.
> 
Doesn't need to be more sophisticated - if we overwrite a by reading into it, we just can't do that optimization.



The issue I was concerned about was this, but now looking at it closer, isn't that nonsense to begin with? Writing into INA? (which is valid, but I don't think the compiler actually knows or wants to know about shadow registers). Though IDK why it doesn't forward replace `arg01` with `fp` in that case there.
```diff
--- Expect/stest174.pasm	2022-04-04 11:08:32.094854584 +0000
+++ stest174.pasm	2022-04-04 11:08:52.846946156 +0000
@@ -9,10 +9,12 @@
 	add	sp, #4
 	mov	fp, sp
 	add	sp, #8
-	mov	main_tmp001_, #1
-	wrlong	main_tmp001_, fp
+	mov	arg01, #1
+	wrlong	arg01, fp
 	mov	outa, #1
-	mov	ina, #1
+	mov	arg01, fp
+	rdlong	arg01, arg01
+	mov	ina, arg01
 	mov	sp, fp
 	sub	sp, #4
 	rdlong	fp, sp
@@ -25,8 +27,8 @@
 	ret
```

**Pull request merged**
