### PR TITLE
Add tilde as alternative to disable optimization

### PR DESCRIPTION
**Pull request by Wuerfel21**
bash seems to (sometimes?) try to parse the ! as something else, even in double quotes...

### CODE REVIEW

**Comment by Wuerfel21** [comment]
oh, the CI stuff ended up in here as well.... eh, whatever

**Comment by drawkula** [comment]
> bash seems to (sometimes?) try to parse the ! as something else, even in double quotes...

Use single quotes instead?
```

(yeti@kumari:1)~$ echo 'midwinter \o/'
midwinter \o/
(yeti@kumari:1)~$ echo "!!"
echo "echo 'midwinter \o/'"
echo 'midwinter \o/'
(yeti@kumari:1)~$ echo 'midwinter \o/'
midwinter \o/
(yeti@kumari:1)~$ echo '!!'
!!
```

**Comment by Wuerfel21** [comment]
Ah, that's nice to know. IMO it's still useful to be able to use the tilde though, that works without any quotes

**Comment by totalspectrum** [comment]
Thanks, Wuerfel

**Pull request merged**
