### PR TITLE
CORDIC reordering optimization

### PR DESCRIPTION
**Pull request by Wuerfel21**
From the land of procrastination, I bring ye another (very unfinished) optimization.

Basically, moves surrounding instructions into the space between QMUL and GETQX.

image

```spin
VAR
 long lmao
PUB main() | a
    a := ina
    lmao += 9
    outa := a*50
```
```
_main
	mov	_var01, ina
	qmul	_var01, #50
	rdlong	_var02, objptr
	add	_var02, #9
	wrlong	_var02, objptr
	getqx	outa
_main_ret
	ret
```

As said, only half finished (can only pull instructions down right now, have to write the other direction block finding algorithm still) and probably full of bugs.
Also changed unsigned divide and signed divide with a constant to use QDIV instead of a function call. In the former case, that's a no-brainer, in the latter it comes at the expense of (usually, depending on context) one additional instruction.

### CODE REVIEW

**Comment by Wuerfel21** [comment]
Ok, with latest fixes it withstands the might of Spin Hexagon, so might aswell un-draft the PR.
Feel free to test.

**Comment by Wuerfel21** [comment]
Pushed some more assorted nonsense that I thought of while scrolling around the files.

**Comment by Wuerfel21** [comment]
Note: latest commit fixes a latent bug wherein `ApplyConditionAfter` doesn't actually transform inherently flag-using ops (WRC/MUXC/DRV/NEGC, etc) and stops applying conditions after any flag write, even it just made that instruction dead (and a couple other potential issues).

**Comment by Wuerfel21** [comment]
I don't think you should've removed the `if (InstrUsesFlags(ir,setc|setz)) WARNING(NULL,"Internal warning. Couldn't ApplyConditionAfter");`, The reason I rewrote that function to begin with is because something seems to rely on it actually eliminating all flag use, thus the warning if it fails that (which as-is should be unreachable, since I think I covered all the flag use cases).

**Comment by totalspectrum** [comment]
That's a tricky one, because in fact a lot of programs do have generic instructions (like coginit) that ApplyConditionAfter gets applied to when -O2 is used -- the default set of tests (in "make test") produced a ton of those warnings. I've checked in some changes to give more information to the optimizer so I hope InstrusesFlags(ir, setc|setz) and hence ApplyConditionAfter is more accurate now.

**Comment by Wuerfel21** [comment]
Ah. I don't actually run the test suite locally because windoze is a slow bum (I could probably literally boot a light linux VM, clone the repo, build the code qnd run the test before windows has even ran half the tests). And the CI didn't generate any warnings...

**Pull request merged**
