### PR TITLE
More optimizer stuff

### PR DESCRIPTION
**Pull request by Wuerfel21**
Forgot to PR this branch, lol.

Basically,
 - when comparing with a constant, try to change to a compare that only uses C
 - when doing a compare where only C is needed, don't set Z also
 - some stuff related to move optimization

### CODE REVIEW

**Comment by totalspectrum** [comment]
Thanks for your improvements!

I merged most of this, but disabled the constant manipulation because it pessimized some maxs/mins sequences. I don't think they're hard to fix, but that seemed the riskiest part of the change anyway and I'd like to think about it some more.

**Comment by Wuerfel21** [comment]
Well, that was also the most interesting part of the change. Turns this here 4-instruction sequence into 2 instructions:
```
	cmps	local05, ##-1 wcz
 if_b	mov	local18, #1
 if_ae	neg	local18, #1
```
I've also tried it on P1 Spin Hexagon and it reduced the number of constant registers needed, so it's a plus there, too.

Can you give an example for the kind of thing that gets pessimized?

**Comment by totalspectrum** [comment]
Hmmm, I'm surprised it would touch that sequence, since the conditions already only involve C and not Z.

The pessimization showed up in stest206.bas, where a sequence that used to come out as:
```
   maxs arg01, #127 wc,wz
```
is instead coming out as:
```
    cmps arg01, #128 wc
if_ae mov arg01, #127
```
It's probably easy enough to add another peephole optimization for this. I am a bit worried about whether there might be cases where `x <= y` is not identical to `x < y+1`; mathematcially they are the same, of course, but at $8000_0000 and $FFFF_FFFF there can be differences.

**Comment by Wuerfel21** [comment]
> Hmmm, I'm surprised it would touch that sequence, since the conditions already only involve C and not Z.

Oh, indeed yes, I think that was the wrong one (or pulled from version before the loop compare change?). IDK, can't find the one anymore. Just imagine it being if_a/if_be instead.

> It's probably easy enough to add another peephole optimization for this. I am a bit worried about whether there might be cases where x <= y is not identical to x < y+1; mathematcially they are the same, of course, but at $8000_0000 and $FFFF_FFFF there can be differences.

They are the same, as long as y != INT_MAX.

**Comment by Wuerfel21** [comment]
In the new peephole code:
`if ( peep_ops[opnum]->val != dst->val+1 )`
Isn't the val field `intptr_t` ? that'd give different results between 32b/64b builds.

**Comment by totalspectrum** [comment]
Hmmm, both vals are the same type, so I think they should be OK, but I'll add a cast just to be sure.

**Comment by Wuerfel21** [comment]
I feel there still is an overflow issue in there. If there is this (which always sets x to -1)
```
      cmp x,#0 wc
if_ae mov x,#-1
```
it'd turn that into `max x,#-1`, which is a no-op, right?

**Pull request merged**
